## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

notifications:
  email: false

matrix:
  include:  
  # Linux
  - os: linux
    julia: 1.4
  # MacOS
  - os: osx
    julia: 1.4
    osx_image: xcode11
  # Windows
  - os: windows
    julia: 1.4    
  # Documentation
  - stage: "Documentation"
    julia: 1.0
    os: linux
    script:
      - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                  Pkg.develop(PackageSpec(path=pwd()));
                                  Pkg.build("FINUFFT")'
      - julia --project=docs/ docs/make.jl
    after_success: skip

# Build script is hardwired to gcc9 on MacOS
before_script: # homebrew for mac
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew unlink gcc && brew link gcc@9; fi

coveralls: true
